name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    uses: modwire/modwire-architecture/.github/workflows/python-release-build.yml@workflows-v1
    with:
      release-tag: ${{ github.event.release.tag_name }}
      python-version: "3.12"

  publish-github-assets:
    needs: build
    uses: modwire/modwire-architecture/.github/workflows/python-release-assets.yml@workflows-v1
    with:
      release-tag: ${{ github.event.release.tag_name }}
    permissions:
      contents: write
